const isLogged = require('../mw/isLogged')

module.exports = function (app) {
  app.use('/', isLogged, require('./home'))
  app.use('/login', require('./login'))
  app.use('/restablecerPassword', require('./restablecerPassword'))
  app.use('/parametros', isLogged, require('./parametros'))
  app.use('/users', isLogged, require('./users'))
  app.use('/pacientes', isLogged, require('./pacientes'))
  app.use('/profesionales', isLogged, require('./profesionales'))
  app.use('/sedes', isLogged, require('./sedes'))
  app.use('/changePassword', isLogged, require('./changePassword'))
  app.use('/mi-perfil', isLogged, require('./mi-perfil'))
  app.use('/formularios', isLogged, require('./formularios'))
  app.use('/servicios', isLogged, require('./servicios'))
  app.use('/citas', isLogged, require('./citas'))
  app.use('/historias-clinicas', isLogged, require('./historias-clinicas'))
  app.use('/facturas', isLogged, require('./facturas'))
  app.use('/informes', isLogged, require('./informes'))
  app.use('/cargue_documento', isLogged, require('./cargue_documento'))
  app.use('/downloadHistory', isLogged, require('./downloadHistory'))
  app.use('/certificado', isLogged, require('./certificado'))
  app.use('/firmaPaciente', isLogged, require('./firmaPaciente'))
  app.use('/configuracion/textConsentimiento', isLogged, require('./textConsentimiento'))
  app.use('/remision', isLogged, require('./remision'))
  app.use('/casoFallido', isLogged, require('./casoFallido'))
  app.use('/adminDatos', isLogged, require('./adminDatos'))
  app.use('/administrarSupervisor', isLogged, require('./administrarSupervisor'))
  app.use('/descargarInformes', isLogged, require('./descargarInformes'))
}
