/* eslint-disable camelcase */
// TODO RUTA: Crear admin de sedevar express = require('express');
const express = require('express')
const router = express.Router()
const create = require('./create')
const buscarIpsPri = require('./getepspri')
const getAll = require('./getAll')
const getAllProfesional = require('./getAllProfesional')
const updatePassword = require('./updatePassword')
const getByUsername = require('./getByUsername')
const update = require('./update');
const updateIdprofe = require('./updateIdprofe');
const EnEsperaUp = require('./EnEsperaUp');
const EnEsperaGet = require('./EnEsperaGet');
const recepcionPacienteGet = require('./recepcionGet')
const recepcionPaciente = require('./recepcionSave')
const informeSave = require('./informeSave')
const informeGet = require('./informeGet')
const informeUp = require('./informeUp')
const resumenHcSave = require('./resumenHcSave')
const resumenHcGet = require('./resumenHcGet')
const resumenHcUp = require('./resumenHcUp')
const cierreSave = require('./cierreSave')
const cierreGet = require('./cierreGet')
const cierreUp = require('./cierreUp')
const seguimientoSave = require('./seguimientoSave')
const seguimientoGet = require('./seguimientoGet')
const seguimientoUp = require('./seguimientoUp')
const getAllPacienteSup = require('./getAllPacienteSup')
const isLoggedAPI_SA_AS_PR_PA = require('../../mw/isLoggedAPI_SA_AS_PR_PA')
const isLoggedAPI_SA_AS_PR = require('../../mw/isLoggedAPI_SA_AS_PR')

/* GET home page. */

router.post('/', isLoggedAPI_SA_AS_PR, create)
router.get('/buscarips/',buscarIpsPri)
router.get('/getAllProfesional/', isLoggedAPI_SA_AS_PR_PA, getAllProfesional)
router.get('/getAllPacienteSup/:sede/:id', getAllPacienteSup)
router.get('/', isLoggedAPI_SA_AS_PR_PA, getAll)
router.patch('/updatePassword/:_id', isLoggedAPI_SA_AS_PR, updatePassword)
router.get('/username/:username', isLoggedAPI_SA_AS_PR_PA, getByUsername)
router.patch('/update',isLoggedAPI_SA_AS_PR_PA, update)
router.patch('/updateIdprofe',isLoggedAPI_SA_AS_PR_PA, updateIdprofe)
router.patch('/EnEsperaUp',isLoggedAPI_SA_AS_PR_PA, EnEsperaUp)
router.get('/EnEsperaGet/:sede', isLoggedAPI_SA_AS_PR_PA, EnEsperaGet)
router.post('/recepcionPaciente', isLoggedAPI_SA_AS_PR, recepcionPaciente)
router.get('/recepcionPacienteGet/:idSede/:idUser', isLoggedAPI_SA_AS_PR_PA, recepcionPacienteGet)
router.post('/informeSave', isLoggedAPI_SA_AS_PR, informeSave)
router.get('/informeGet/:idSede/:idUser', isLoggedAPI_SA_AS_PR_PA, informeGet)
router.patch('/informeUp/:_id', isLoggedAPI_SA_AS_PR_PA, informeUp)
router.post('/resumenHcSave', isLoggedAPI_SA_AS_PR, resumenHcSave)
router.patch('/resumenHcUp/:_id', isLoggedAPI_SA_AS_PR_PA, resumenHcUp)
router.post('/cierreSave', isLoggedAPI_SA_AS_PR, cierreSave)
router.get('/cierreGet/:idSede/:idUser', isLoggedAPI_SA_AS_PR_PA, cierreGet)
router.get('/resumenHcGet/:idSede/:idUser', isLoggedAPI_SA_AS_PR_PA, resumenHcGet)
router.patch('/cierreUp/:_id', isLoggedAPI_SA_AS_PR_PA, cierreUp)
router.post('/seguimientoSave', isLoggedAPI_SA_AS_PR, seguimientoSave)
router.get('/seguimientoGet/:idSede/:idUser', isLoggedAPI_SA_AS_PR_PA, seguimientoGet)
router.patch('/seguimientoUp/:_id', isLoggedAPI_SA_AS_PR_PA, seguimientoUp)
module.exports = router
